tutorial/urls.py
from django.conf.urls import url, include

from .views import IndexView, TopicView, TutorialView, subscribe_view

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    # This needs to be here because of the rule of topic url
    url(r'^subscribe/$', subscribe_view, name='subscribe'),
    url(r'^(?P<slug>[\w-]+)/$', TopicView.as_view(), name='topic'),
    url(r'^(?P<topic_slug>[\w-]+)/(?P<slug>[\w-]+)/$', TutorialView.as_view(),
        name='tutorial'),
]

tutorial_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tutorial.urls', namespace='tutorial')),
]

tutorial/models.py
from django.db import models
from django.urls import reverse

from ckeditor.fields import RichTextField

from adminsortable.models import SortableMixin

from django_extensions.db.models import TimeStampedModel


class AdminSortableModel(SortableMixin):
    order = models.PositiveIntegerField(default=0, editable=False,
                                        db_index=True)

    class Meta:
        abstract = True


class Topic(AdminSortableModel, TimeStampedModel):
    """
    This model basically stores what is the tutorial topic about:
    like django, python or whatever
    """
    name = models.CharField(max_length=255, unique=True,
                            help_text='High Level: Python or Ruby or ROR')
    slug = models.SlugField(unique=True) # by default max length 50
    body = RichTextField(blank=True)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tutorial:topic', args=[self.slug])

    class Meta:
        ordering = ['order']


class Category(AdminSortableModel, TimeStampedModel):
    """
    There can be category styled tutorial, this model handles that
    """
    name = models.CharField(max_length=255)
    # If your tutorial website is niche based like pythontutorial.com
    # you won't be creating topic so this is optional
    topic = models.ForeignKey(Topic, blank=True, null=True,
                              help_text='If you have used topic make sure'
                                        'to input it here',
                              related_name='categories')
    body = RichTextField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['order']

    def get_absolute_url(self):
        tutorial = self.tutorials.first()
        if tutorial:
            return reverse('tutorial:tutorial',
                       args=[self.topic.slug, tutorial.slug])


class Tutorial(AdminSortableModel, TimeStampedModel):
    """
    Tutorial will belong to Category and Topic
    """
    # Enforcing that this tutorial website will have category
    # This is how I like it
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, related_name='tutorials')
    body = RichTextField()

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('tutorial:tutorial',
                       args=[self.category.topic.slug, self.slug])

    def next_tutorial(self):
        tutorial = self.category.tutorials.filter(order=self.order+1)
        if tutorial.exists():
            tutorial = tutorial[0]
            return reverse('tutorial:tutorial',
                           args=[tutorial.category.topic.slug, tutorial.slug])

    def previous_tutorial(self):
        tutorial = self.category.tutorials.filter(order=self.order-1)
        if tutorial.exists():
            tutorial = tutorial[0]
            return reverse('tutorial:tutorial',
                           args=[tutorial.category.topic.slug, tutorial.slug])


    class Meta:
        ordering = ['order']


class Subscriber(TimeStampedModel):
    email = models.EmailField()

    def __str__(self):
        return self.email

tutorial/forms.py
from django import forms

from .models import Subscriber


class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ('email',)

tutorial/views.py
from django.views.generic import TemplateView, DetailView
from django.http import HttpResponse

from .models import Topic, Category, Tutorial, Subscriber

from .forms import SubscriberForm

class IndexView(TemplateView):
    """
    This is the homepage, I would like to call main page of my website Index
    What do we wanna show here:
    1) Subscribe, we want to collect as much user email as possible and send
    them nice content and come back to our website.
    2) Topics and their categories -> ie if you we have topic else (max 5)
    3) Categories and the tutorial title -> (max 5)
    """
    template_name = 'tutorial/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        topics = Topic.objects.all()
        # If we have topic send only topic to context
        # we will get categories from set_objects
        if topics.exists():
            context['topics'] = topics
        else:
            # if we don't have topic we send the categories and get tutorial
            # from set_objects
            context['categories'] = Category.objects.all()
        return context


class TopicView(DetailView):
    """
    This the topic view, this is the page when clicks on the topic
    In this page we will display categories of corresponding topic in a card
    and all the tutorials
    """
    template_name = 'tutorial/topic.html'

    model = Topic


class TutorialView(DetailView):
    """
    This is where we show the tutorial
    /topic-slug/tutorial-slug/
    """
    template_name = 'tutorial/tutorial.html'

    model = Tutorial


def subscribe_view(request):
    """
    Subscribe the user to python guides
    """
    if request.is_ajax() and request.method == 'POST':
        form = SubscriberForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            subscriber = Subscriber.objects.filter(email=email)
            # Only add if email doesn't exist before
            if not subscriber.exists():
                Subscriber.objects.create(email=email)
            return HttpResponse(status=200)

    return HttpResponse(status=400)

templates/tutorial/base.html
{% load nav_menu %}
{% load static %}
{% load flatpages %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>We provide you with awesome upto date tutorials!</title>

  <!-- CSS  -->
  <link rel="icon" href="{% static 'images/favicon.ico' %}">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
        rel="stylesheet">
  <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<header>
  <nav class="blue-grey darken-1" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="{% url 'tutorial:index' %}"
         class="brand-logo">Python Guides</a>
      {% nav_menu %}
    </div>
  </nav>
</header>

<main>
  {% block home_page_banner %}{% endblock %}
  <div class="container">
    <div class="section">
      {% block content %}{% endblock %}
    </div>
    <br><br>
  </div>
</main>

<footer class="page-footer blue-grey darken-1">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Stay updated about Python</h5>
        {% subscriber_form %}
      </div>
      <div class="col l6 s12 center">
        {% get_flatpages as flatpages %}
        <ul>
          {% for page in flatpages %}
            <li><a class="white-text"
                   href="{{ page.url }}">{{ page.title }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      Copyright © Python Guides
    </div>
  </div>
</footer>


<!--  Scripts-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<script type="text/javascript">
    var subscriberForm = $("#subscriber-form");
    subscriberForm.submit(function (event) {
        event.preventDefault();
        $.ajax({
            url: subscriberForm.attr("action"),
            type: subscriberForm.attr("method"),
            data: subscriberForm.serialize(),
            statusCode: {
                200: function (html) {
                    subscriberForm.hide();
                    $("#subscriber-success").show();
                }
            }
        });
    });
</script>
</body>
</html>

templates/tutorial/includes/form.html
<form class="col s12" id="subscriber-form" method="post"
      action="{% url 'tutorial:subscribe' %}">
  {% csrf_token %}
  <div class="row">
    <div class="input-field col s6">
      <input id="id_email" type="email" class="validate" name="email">
      <label for="id_email" data-error="Opps! Invalid Email">Enter your
        Email</label>
    </div>
    <div class="input-field col s4" id="subscribe-button">
      <button class="btn waves-effect blue darken-1" type="submit"
              name="action">
        Subscribe
      </button>
    </div>
  </div>
</form>
<div id="subscriber-success">
  Thank you for subscribing.
</div>

templates/tutorial/includes/nav_menu.html
<!--TODO Make it mobile responsive-->
<ul class="right hide-on-med-and-down">
    {% for item in menu %}
        <li><a href="{{ item.get_absolute_url }}">{{ item }}</a></li>
    {% endfor %}
</ul>

templates/tutorial/index.html
{% extends 'tutorial/base.html' %}
{% block home_page_banner %}
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      <h2 class="header center light-blue-text">Python Programming
        tutorials</h2>
      <div class="row center">
        <h5 class="header col s12 light">Learn while doing..</h5>
      </div>
    </div>
  </div>
{% endblock %}
{% block content %}
  <div class="row">
    {% if topics %}
      {% for topic in topics %}
        <div class="col s12 m4">
          <div class="card blue-grey darken-2 tutorial-card">
            <div class="card-action center-align">
              <a href="{{ topic.get_absolute_url }}">{{ topic }}</a>
            </div>
            <div class="card-content white-text">
              <ul>
                {% for category in topic.categories.all %}
                  <li><a
                      {% if category.get_absolute_url %}href="{{ category.get_absolute_url }}" {% endif %}>{{ category }}</a>
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      {% for category in categories %}
        <div class="col s12 m4">
          <div class="card blue-grey darken-2">
            <div class="card-action center-align">
              <a href="{{ category.get_absolute_url }}">{{ category }}</a>
            </div>
            <div class="card-content white-text">
              <ul>
                {% for tutorial in category.tutorials.all %}
                  <li>{{ tutorial }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      {% endfor %}
    {% endif %}
  </div>
{% endblock %}

templates/tutorial/topic.html
{% extends 'tutorial/base.html' %}
{% block content %}
  <div class="row">
    <h3 class="header center light-blue-text">{{ object }}</h3>
    <div class="underline"></div>
  </div>
  <div class="row">
    {{ object.body|safe }}
  </div>
  <div class="row">
    {% for category in object.categories.all %}
      <div class="col s12 m4">
        <div class="card blue-grey darken-2 tutorial-card">
          <div class="card-action center-align">
            <a href="{{ category.get_absolute_url }}">{{ category }}</a>
          </div>
          <div class="card-content white-text">
            <ul>
              {% for tutorial in category.tutorials.all %}
                <li><a href="{{ tutorial.get_absolute_url }}">{{ tutorial }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

templates/tutorial/tutorial.html
{% extends 'tutorial/base.html' %}
{% block content %}
  <div class="row">
    <h3 class="header center light-blue-text">{{ object }}</h3>
    <div class="underline"></div>
  </div>
  <div class="row">
    {{ object.body|safe }}
  </div>
  <div class="row">
    <div class="underline"></div>
    <br>
    {% if object.previous_tutorial %}
    <a class="blue-grey lighten-1 btn left" href="{{ object.previous_tutorial }}">
      <i class="material-icons left">chevron_left</i>Previous</a>
    {% endif %}
    {% if object.next_tutorial %}
    <a class="blue-grey lighten-1 btn right" href="{{ object.next_tutorial }}">
      <i class="material-icons right">chevron_right</i>Next</a>
    {% endif %}
  </div>
{% endblock %}